### ISSUE TITLE
Error `unknown repo 'git'`

### ISSUE THREAD

**Issue by ehmicky** [getsentry/sentry-netlify-build-plugin#6] opened 2020-05-28 19:48 UTC
The following error is happening in some build:

```
Command failed: /opt/buildhome/.netlify-build-plugins/node_modules/@sentry/cli/sentry-cli releases set-commits 74c7...0f06 --commit git@gitlab.com:the-hq/hq.web.app@74c7...0f06
error: Unknown repo 'git'

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
 
    child_process.js:303:12 ChildProcess.exithandler
    events.js:310:20 ChildProcess.emit
    internal/child_process.js:1021:16 maybeClose
    internal/child_process.js:286:5 Process.ChildProcess._handle.onexit
```

I am not completely sure whether the `Unknown repo 'git'` is a user error or not. If it is a user error, then this falls under #3. Do you happen to have some insights on this?

**Comment by jonesphillip** [comment] 2020-05-29 00:14
Looks like the issue here is that the repo url is expected to be in the format:`https://github.com/org/repo`

This error is caused by repos in this format `git@gitlab.com:org/repo`. Should be resolved in next release. Let me know if it persists afterwards.

**Closed by jonesphillip** 2020-05-29 00:14 UTC

**Comment by ehmicky** [comment] 2020-05-29 10:43
Thanks for the explanation @jonesphillip!
